import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import LineHeader from '@/components/LineHeader'
import Header from '@/components/Header'
import { Page, PageContainer, PageFullWidthContent } from './themes/globalStyle'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>CY Acessórios</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>

        <PageFullWidthContent>
            <LineHeader />
        </PageFullWidthContent>

        <PageContainer>
          <Page>
            <Header />
            
          </Page>
        </PageContainer>
      
      </main>
    </>
  )
}
